name: C CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -yq \
                   libimlib2-dev \
                   librsvg2-dev \
                   libcairo2-dev \
                   libwebp-dev \
                   libcurl4-gnutls-dev \
                   libx11-dev \
                   libxft-dev \
                   freetype2-doc \
                   libfontconfig1-dev \
                   giflib-tools \
                   libexif-dev

    - name: Run make
      run: make
